{% set name = "pyswmm" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyswmm-{{ version }}.tar.gz
  sha256: 1c3e1f7532a912a3ae8318713e35444a5bde1033bc0ed1d3567dfa35b5b6b36a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - setuptools >=68.2
    - pip
  run:
    - python >=3.7
    - swmm-toolkit >=0.9.0
    - julian >=0.14
    - aenum >=3.1.11
    - packaging

test:
  imports:
    - pyswmm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenWaterAnalytics/pyswmm/wiki
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python Wrapper for SWMM5 API
  doc_url: https://pyswmm.readthedocs.io
  dev_url: https://github.com/OpenWaterAnalytics/pyswmm/

extra:
  recipe-maintainers:
    - lrntct
