{% set name = "pyswmm" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e82572bcf9de951272d24efd216b88ef473bcad717a72639d0a73779cb94253d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - six
    - swmm

about:
  home: https://github.com/OpenWaterAnalytics/pyswmm/wiki
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python Wrapper for SWMM5 API
  doc_url: https://pyswmm.readthedocs.io
  dev_url: https://github.com/OpenWaterAnalytics/pyswmm/

extra:
  recipe-maintainers:
    - lrntct
